- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
* Updating vanilla workflows with -DUSE_WASM_COMPATIBLE_MARIAN=off
* Boost: Replacing with OS Boost for Ubuntu Builds
> CI Fixes: vanilla bergamot-translator

- .github/workflows/native-custom_marian-mac.yml
- .github/workflows/native-custom_marian-ubuntu.yml
- .github/workflows/native-full_marian-mac.yml
- .github/workflows/native-full_marian-ubuntu.yml
- CMakeLists.txt
- app/CMakeLists.txt
- doc/marian-integration.md
- src/translator/CMakeLists.txt
- src/translator/batch_translator.h
- src/translator/batcher.h
- src/translator/service.cpp
- src/translator/service.h
- Updates marian submodule (brings loading models from byte array change too which is required here)
- Adds workflows for building custom marian natively on mac and ubuntu
> Marian submodule update

- src/translator/CMakeLists.txt
> Fix the target_include_directories

- src/translator/pcqueue.h
Also undo formatting changes somebody made from my upstream version
PCQueue started out on https://github.com/kpu/preprocess/blob/master/util/pcqueue.hh and somebody changed the formatting from there.  I've undone that.  
Lightly tested in https://github.com/kpu/pcqueue/actions
Partially does #105.
> Windows PCQueue support without Boost

- wasm/CMakeLists.txt
This PR fixes https://github.com/browsermt/bergamot-translator/issues/144
- Just adds 2 linker flags
> Expose specific JS functions while building wasm

- app/service-cli.cpp
- src/translator/byte_array_util.cpp
- src/translator/byte_array_util.h
- src/translator/definitions.h
- src/translator/service.cpp
- src/translator/service.h
- wasm/bindings/TranslationModelBindings.cpp
This PR addresses https://github.com/browsermt/bergamot-translator/issues/133 (2) and (3) which aims to bundle all byte-array members together.
> Bundle AlignedMemory inputs with MemoryBundle

- .github/workflows/push-browsermt-main-to-mozilla-main.yml
Designed to run in mozilla/bergamot-translator
> GitHub action to push browsermt/main branch to mozilla/bergamot-translator every hour

- .github/workflows/native-ubuntu.yml
- app/CMakeLists.txt
- app/bergamot-translator-app.cpp
- src/translator/service.cpp
- src/translator/service.h
This was formerly a second half of #142, which cannot go in without making a mess in the BRT repo until #175 gets in. Therefore, we'll queue it behind.
> translateMultiple only for WASM

- .circleci/config.yml
- build-wasm.sh
To consume pre-built wasm artifacts without wormhole
> CircleCI non-wormhole build artifacts

- wasm/test_page/bergamot.js
- wasm/test_page/worker.js
This PR modifies the wasm test page to verify whether the new feature (loading and working with multiple translation models) works in the engine for wasm target.
It fixes a part of the issue https://github.com/mozilla/bergamot-translator/issues/58
> Wasm test page for new Service interface (Multiple Models)

- src/translator/response.h
- src/translator/response_builder.cpp
- src/translator/response_options.h
- wasm/bindings/response_options_bindings.cpp
- wasm/test_page/js/worker.js
> Deprecate hardAlignment in favour of softAlignment

- wasm/test_page/start_server.sh
A small refactoring to run script from any directory
> Make script run from any directory

- doc/requirements.txt
Copying over from https://github.com/marian-nmt/marian-dev/pull/894, will merge if builds pass.
> Constrain mistune to fix docs CI

- wasm/test_page/js/worker.js
- Print source text received in the response
- Print no. of block elements in the input
> Additional logs in JS translation worker

- .circleci/config.yml
- Robust artifact presence check
- Variable name refactoring
- Storing only those artifacts that are required
- Remove commit sha from the names of the Github Releases
- Use BERGAMOT_VERSION file contents for Git Tag names
> CI: Circle CI config script update

- src/translator/translation_model.cpp
- src/translator/translation_model.h
See #293 for speed comparison.
> Defer model loading to parallel worker thread

- wasm/test_page/js/worker.js
- Additionally, free all the objects properly that were constructed for translation api
> JS: Refactoring wasm test page

- wasm/test_page/js/index.js
I noticed that Bulgarian wasn't on the list.
This change uses the registry.json file that's already being loaded by worker.js to populate the language dropdowns. I'm using [Intl.DisplayNames](http://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames) to show the full language names.
> JS: Update languages & use Intl API for their display names

- bindings/python/repository.py
Fixes #430. 
Tries to check if `models.json` is downloaded first, if it is we use it. If not, fall back to attempting to fetch it from the network.
> Python: Work offline if models are available

- .github/workflows/build.yml
Adds extra python wheels for MacOS
> MacOS Wheels
