browsermt/bergamot-translator

.github/workflows/macos-custom-marian-native.yml, .github/workflows/macos-custom-marian-wasm.yml, .github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, CMakeLists.txt, app/CMakeLists.txt, doc/marian-integration.md, src/translator/CMakeLists.txt, src/translator/TranslationModel.cpp, src/translator/TranslationModel.h, src/translator/batch_translator.cpp, src/translator/batch_translator.h, src/translator/batcher.cpp, src/translator/batcher.h, src/translator/service.cpp, src/translator/service.h, src/translator/service_base.cpp, src/translator/service_base.h
* Adds a permanent _ci-sandbox_ branch to all `.yml` files to force push and test in case CI breaks. I vote to keep this in source.
* Rewrites NonThreaded and threaded implementations with minimal `ifdefs`.
* Should fix #41: That this doesn't happen in the concurrent queuing development branch should point to something with the threading mechanism with ifdefs faults. Inspection through gdb found several places where threads were crashing, initialized with arbitrary values. These potentially leads to issues with the shared_ptrs as well. The applied solution is to not have threads at all in the non-threaded code and have legit (properly initialized) threads in the multithreaded code. The shared parts are now redirected to a base class (ServiceBase). 
* bergamot-translator-app talks only to …
=> Improve threaded/non-threaded paths

.github/workflows/macos-custom-marian-wasm.yml, README.md, wasm/patch-artifacts-enable-wormhole.sh, wasm/test_page/bergamot.html, wasm/test_page/start_server.sh
This fixes https://github.com/browsermt/bergamot-translator/issues/49
- Patches wasm artifacts to enable wormhole so that optimized inference can happen
- Updated README
- Updated corresponding github workflow
=> Patch WASM artifacts to run optimized (wormhole enabled) inference

app/bergamot-translator-app.cpp
I need a simple app for evaluation that should be able to accept newline-separated texts in stdin, translate them separately and output results to stdout. Basically the same behavior as `marian-decoder`. The motivation to use `bergamot-translator` and high-level API is to be as close to the production setup in Firefox as possible.
@abhi-agg suggested fixing `bergamot-translator-app` to support this functionality.
=> Change bergamot app to process stdin texts

.github/workflows/native-full_marian-ubuntu.yml
CI is failing due to some change at github https://github.com/browsermt/bergamot-translator/pull/69/checks?check_run_id=2245404337
=> Explictly install gcc version and use 8

app/bergamot-translator-app-bytearray.cpp, src/TranslationModel.h, src/translator/TranslationModel.cpp, src/translator/service.h
Removes hack that shouldn't have been allowed in from #69 by propagating AlignedVector.
=> Make AlignedMemory the means of passing in memory

src/translator/byte_array_util.cpp
Validate that the binary file you are trying to load is not truncated.
=> Rudimentary validator for binary files

src/translator/batch_translator.cpp
The boolean passed to the `ExpressiongGraph` class actually sets the inference mode, it doesn't deal with any optimisations.
=> Clarify misleading comment

src/translator/definitions.h
- AlignedMemory is AlignedVector<char> now instead of AlignedVector<const void*>
- This solves the issue of allocating 8x of the actual required memory for
loading files as bytes
This PR fixes https://github.com/browsermt/bergamot-translator/issues/110
=> Changed underlying template parameter of AlignedMemory class

.github/workflows/windows.yml
This pull request updates the marian-dev submodule to the latest version of browsermt and restores the windows workflow.
The marian-dev changes allow to use the apple accelerate framework when running on apple machine and allows for compilation with apple clang. I also fixed they way `BLAS_FOUND` was being defined because it was preventing BLAS_FOUND to be set in some rare cases.
Finally, the windows workflow is fixed up, but will fail until some ssplit-cpp changes land. Those will go to a separate pull request, as they involve a few small changes to the CMakeLists.txt.
=> Windows workflows and mac framework accelerate draft

src/translator/request.cpp
Fixes https://github.com/browsermt/bergamot-translator/issues/101.
ResponseBuilder is called with empty histories to trigger a valid but
mostly-empty response.
=> Handle empty translation requests

src/translator/parser.h, src/translator/service.h
- parseOptions() function now validates the parsed options
based on the validate argument
The PR fixes https://github.com/browsermt/bergamot-translator/issues/112
=> Control validating the config options via a boolean flag

wasm/test_page/bergamot.html
This PR enables using wasm test page for inference by passing models and shortlist as bytes (instead of files) to the translation engine
=> Functional wasm test page

wasm/README.md, wasm/test_page/bergamot.html
1. Loading Model and Shortlist as bytes caused a reduction in inference speed
1. Added the missing `gemm-precision` option in config of wasm test page that improved it
2. Improved wasm README
1. The README is updated to show the usage of JS APIs
=> Improve inference speed for model and shortlist bytes

wasm/patch-artifacts-enable-wormhole.sh, wasm/test_page/bergamot.html
The PR:
- Improves the script that patches wasm artifacts to enable simd wormhole
- Introduces a more robust pattern matching of wasm instantiation API in the generated wasm artifacts
- This fixes the issue observed in https://github.com/browsermt/bergamot-translator/pull/87#discussion_r624071379
- Fixes wasm test page for loading EN->DE vocabulary properly
- With latest [bergamot-models](https://github.com/mozilla-applied-ml/bergamot-models/tree/main/prod), it wasn't working for EN->DE
- Now it works
=> Improve script to patch wasm artifacts and load EN->DE vocabulary in wasm test

.github/workflows/wasm-custom_marian-mac.yml, .github/workflows/wasm-custom_marian-ubuntu.yml, README.md, wasm/CMakeLists.txt, wasm/README.md, wasm/patch-artifacts-enable-wormhole.sh, wasm/test_page/start_server.sh
- Build the wasm artifacts in the top level build folder instead of build/wasm folder
- Robust scripts to patch wasm artifacts and starting the http server
- **There is no change in what they were doing before**
- Just added an argument to accept the folder where the wasm artifacts reside
- Updated root level README
- To not package model and lexical files in wasm binary since they are provided at run time
- It avoids bloating up the wasm binary significantly
=> Improved wasm scripts and README

wasm/CMakeLists.txt
This PR includes a couple of changes that makes the glue code compatible with the current bergamot-browser-extension implementation. 
WorkerFS is used to mount remotely downloaded model files (including vocab files) in the emscripten's file system so that no files needs to be bundled in the wasm artifacts. 
Avoiding node.js-code in Emscripten glue-code allows the glue code to be integrated properly in the extension's webpack build configuration.
=> Extension desired changes

src/translator/pcqueue.h
I had misread the documentation of WaitForSingleObject in https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject
=> Fix busy loop in windows

src/translator/definitions.h
`TokenRanges/SentenceTokenRanges` are all `string_views`/`ByteRange`s, and the ugliness sort-of hidden now by 	`Annotation`.
The UPtr is marian syntax which I don't think this repo will have any use for, use `std::make_unique`, `std::unique_ptr` instead if at all any need be.
=> Remove unused used types TokenRanges, SentenceTokenRanges, UPtr

wasm/bindings/TranslationModelBindings.cpp, wasm/test_page/bergamot.html
This PR fixes https://github.com/browsermt/bergamot-translator/issues/75
- It enables passing **vocabulary** as bytes from JS environment (completes all tasks mentioned in https://github.com/browsermt/bergamot-translator/issues/75#issuecomment-838534866)
- Super small refactoring in bindings class to make it more readable
=> Enable passing Vocabularies as bytes from JS

CMakeLists.txt, README.md, wasm/CMakeLists.txt, wasm/README.md
Model, shortlist and vocabulary files can be passed as bytes. => We can stop packaging these files into wasm during build steps.
This PR:
- Updates READMEs to reflect these changes
- Updates CMakeLists.txt files to remove packaging steps from them
- Updates wasm README to reflect API changes to pass vocab as bytes
=> Remove packaging step from wasm build commands

src/translator/batch_translator.cpp, src/translator/batch_translator.h, src/translator/definitions.h, src/translator/response_builder.cpp, src/translator/response_builder.h, src/translator/service.cpp, src/translator/service.h, src/translator/text_processor.cpp, src/translator/text_processor.h, src/translator/vocabs.h
This PR address https://github.com/browsermt/bergamot-translator/issues/133 (1) which aims to take loadVocabularies() out of Service. 
Introduce `vocabs.h` to include `loadVocabularies()` functionalities.
=> Refactor vocabs in Service

src/tests/annotation_tests.cpp, src/translator/annotation.cpp, src/translator/annotation.h, src/translator/response_builder.cpp, src/translator/text_processor.cpp, src/translator/text_processor.h
This cleans up Annotation to store just offsets where tokens begin and explicitly model the gaps between sentences (as well as before and after).  
Empty sentences and empty space are no longer a special case, they just happen naturally.  https://www.youtube.com/watch?v=UfJljXugLA0
Now that the accessors are simpler, they are in the headers so the compiler can reason about them.  
Still TODO is the two methods for filling Annotation (give it a string or append stuff) could use better cohesiveness and documentation.
=> Rewrite annotation class to remove corner cases

src/translator/definitions.h
This PR addresses https://github.com/browsermt/bergamot-translator/issues/166.
Old version of c++ does not intialise Struct members.
I tested in vahalla, now the build can pass.
=> Fix Unbuntu 16.04 build

src/translator/annotation.cpp
Remove O(N^2) reallocation. Fixes https://github.com/browsermt/bergamot-translator-tests/issues/30. 
<details>
<summary>speed regression-tests pass now</summary>
```
jphilip@var:~/code/bergamot-translator-test-scripts$ MARIAN=/mnt/Storage/jphilip/bergamot-build TIMEOUT=30m BRT_THREADS=40 BRT_EXPECTED_MAXTIME=500 ./run_brt.sh speed-tests/test_wngt20_perf.sh
[05/21/2021 17:02:20] Running on var as process 50502
[05/21/2021 17:02:20] Version: v1.9.56 80e47424 2021-05-18 10:55:11 +0100
[05/21/2021 17:02:20] Build type: Release
[05/21/2021 17:02:20] Using compiler: /usr/bin/c++
[05/21/2021 17:02:20] Using MKL: USE_MKL=ON
[05/21/2021 17:02:20] Using CUDNN:
[05/21/2021 17:02:20] Using SentencePiece: USE_SENTENCEPIECE=ON
[05/21/2021 17:02:20] Using FBGEMM:
[05/21/2021 17:02:20] Unit tests: …
```
=> Remove O(N^2) reallocation

.github/workflows/doc.yml
Uploads latest documentation to repository's gh-pages branch.
There ~~can be~~ is some trickery to do this per version and also latest, like how docs are normally structured. Have latest `v<major>.<minor>.<suffix>` corresponding to releases as well.
Here's demonstration of a successful run on my fork:
* https://github.com/jerinphilip/bergamot-translator/runs/2625000572?check_suite_focus=true
* https://jerinphilip.github.io/bergamot-translator/ (sample-render)
Also could have doxygen warn about undocumented members, but maybe in a later PR.
The yaml is borrowed from @graemenail, upload-artifact ~~cut~~ only on pull request, gh-pages publish moved in.
=> Adding documentation action

src/translator/batcher.cpp, src/translator/batcher.h, src/translator/threadsafe_batcher.cpp, src/translator/threadsafe_batcher.h
This removes the unused `addSentenceWithPriority` function and inlines the one caller it had.
=> Remove addSentenceWithPriority

.github/workflows/wasm-custom_marian-mac.yml, .github/workflows/wasm-custom_marian-ubuntu.yml, README.md, build-wasm.sh
- Set EMSDK version to 2.0.9 to make it consistent
everywhere in repo
- Set parallel make jobs to 2
It resolves the issue because of which PR https://github.com/browsermt/bergamot-translator/pull/165 was created.
=> Consistent EMSDK version and parallel make jobs

.github/workflows/push-browsermt-main-to-mozilla-main.yml
> When you use expressions in an if conditional, you may omit the expression syntax (${{ }}) because GitHub automatically evaluates the if conditional as an expression, unless the expression contains any operators. If the expression contains any operators, the expression must be contained within ${{ }} to explicitly mark it for evaluation. For more information about if conditionals, see "Workflow syntax for GitHub Actions."
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions
Copying over from https://github.com/jerinphilip/gh-workflow-multi-repo-sync-mirror/blob/3ccc0f66ba97e9a3662ade8f9a5e1c421529df0a/.github/workflows/mirror.yml#L23, should work hopefully.
=> Fixing if syntax in periodic push workflow

wasm/CMakeLists.txt
Fixes https://github.com/browsermt/bergamot-translator/issues/161
(The PR https://github.com/browsermt/bergamot-translator/pull/193 fixed one part of the https://github.com/browsermt/bergamot-translator/issues/161, this PR fixes the other part of the same issue)
=> Generating cmake configured project version (.js) file in build folder

src/tests/apps.cpp, src/tests/apps.h, src/tests/cli.cpp
We're not covering a bunch of test-code in the updated tests where QE and Alignments are gone, so removing that bit (was supposed to go in with #184).
#184 got merged before I could get submodule to point to master, second commit.
=> Removing alignments and quality-scores test-code

src/translator/text_processor.cpp
This was causing segfaults for me at OOV analysis (#185), bringing fix in as PR.
=> maxLengthBreak_ -> wrapStep bugfix

src/translator/annotation.h, src/translator/definitions.h, src/translator/response.h, wasm/bindings/response_bindings.cpp, wasm/test_page/bergamot.html
This PR fixes https://github.com/browsermt/bergamot-translator/issues/57
Details:
- Moved `ByteRange` structure to `definitions.h` file as this is a base structure that is used to represent a sentence, word, token etc.
- Added public methods to return sentence byte ranges from Response class
- Doesn't make sense to expose an internal structure `AnnotatedText` just for returning this information to JS
- JS bindings to access sentence byte ranges from wasm module
- wasm test page changes to extract individual sentences from response using these newly developed JS bindings
=> Ability to extract individual sentences in JS

.github/workflows/windows.yml
A cmake change has caused vcpkg to fail without much error message,
which is causing windows workflow runs to fail. Details in the following
link:
* https://github.com/microsoft/vcpkg/issues/18718
To fix, we're going with a version bump in vcpkg. Seeing that run-vcpkg
also seems to have gotten an update, updating run-vcpkg from 7.3 to 7.4
Playing with fire: vcpkg master commit
=> Windows workflow: run-vcpkg7.{3->4}; vcpkg master

README.md
Fixes https://github.com/browsermt/bergamot-translator/issues/206
Updated README to add build instructions for running on other browsers
Tested it on Google Chrome browser (92.0.4515.131 (Official Build) (x86_64)) on Mac OS 11.4
=> Wasm build instructions to run translations on other browsers

.clang-tidy, .github/workflows/coding-styles.yml
Adds a clang-tidy run in addition to the existing clang-format checks.
The clang-tidy checks are not enforced, but is potentially useful to
point to during review.
=> Add a clang-tidy run

wasm/test_page/js/worker.js
Setting this config to `false` allows the quality scores to be returned as log-probability values
=> Update config "skip-cost" to return log probabilities as QE scores

wasm/import-gemm-module.js, wasm/patch-artifacts-import-gemm-module.sh
Fixes https://github.com/browsermt/bergamot-translator/issues/264
List of changes:
- Added file `wasm/import-gemm-module.js` that houses the logic to import and use the optimized gemm when available, otherwise fallback gemm
- Associated refactoring in `wasm/patch-artifacts-import-gemm-module.sh` for this change
Ran [wasm test page](https://github.com/browsermt/bergamot-translator/tree/main/wasm#demo) to test this logic. The optimized gemm is called when run on locally compiled version of firefox browser that exports a dummy implementation for gemm intrinsics. This proves that the logic written here works correctly to invoke an optimized gemm when available in the environment.
cc @yurydelendik @eqrion
=> Import optimized gemm implementation (when available) for wasm target

src/tests/units/html_tests.cpp, src/translator/html.cpp
This merge request contains fixes for several issues:
1. If the model did not have `alignment:soft` in its configuration, `HardAlignment()` would crash & burn.
2. If you had a model that cut the first word of an output into multiple tokens, and the first of those tokens was not the token that had the highest alignment score of all target tokens for that word, there was an invalid array access (because `(size_t)0 - 1 >= 0`…)
3. If you had an empty (i.e. what in XHTML was a self-closing) element at the end of a parent's element contents, or the end of a sentence, you'd get a parse error because that empty element would stay on the stack too long.
4. `&nbsp;` was not recognised. It is now, but translated to a single "␣". So if there was a non-breaking space in the source HTML, it will not …
=> HTML handling improvements

wasm/test_page/js/worker.js
Added `alignment: soft` during translator construction as per https://github.com/browsermt/bergamot-translator/pull/266#issuecomment-982715697 and `ResponseOptions::alignment` to `true` as per https://github.com/browsermt/bergamot-translator/pull/266#issuecomment-982773699
Both of these changes were required for the html text translation to work. Only providing`alignment: soft` during translator construction and not setting `ResponseOptions::alignment` to `true` doesn't give correct results.
=> Updated configuration for html text translation to work in wasm test page

wasm/import-gemm-module.js
- Import optimized gemm implementation only if all the necessary functions
are provided by it, othewise use the fallback gemm
@andrenatal This should fix the issue that you were encountering in the extension
=> More robust logic to import wasm gemm

CMakeLists.txt
@jerinphilip  with this, `DBUILD_ARCH` should work properly for all platforms. I assume you're already passing  it for MacOS build?
=> Proper arch setting on win32

app/cli.h, src/tests/units/CMakeLists.txt, src/tests/units/html_tests.cpp, src/tests/units/xh_scanner_tests.cpp, src/translator/html.cpp, src/translator/parser.cpp, src/translator/parser.h, src/translator/xh_scanner.cpp, src/translator/xh_scanner.h
The HTML parser used internal stack-allocated buffers for text, tags, and attributes. This change replaces them with std::string_view.
This is a fix for #273.
Related issue in warc2text: https://github.com/bitextor/warc2text/issues/32, but less impact because that doesn't use these buffers for text between tags as it does entity decoding at another place.
This change also removes the fallback tag alignment code. Now if there is no alignment information available, no HTML tags will be inserted into the output. This would have already been enforced by #271 by always requesting alignment info from the model if ResponseOptions.HTML was true, so there should be no impact outside of the HTML class and tests. (And if there is the integration tests will call me on it.)
Edit: furthermore, this …
=> Remove value length limit from HTML parser & interpolated alignments

wasm/import-gemm-module.js
Fixes https://github.com/browsermt/bergamot-translator/issues/281
Until the optimized gemm module stops requiring Shared Array Buffer, we can't really use it in Firefox
=> Disabled importing optimized gemm module

.circleci/config.yml
We need a way to auto publish builds to github releases to facilitate the integration with the extension, so this patch introduces that to circle ci whenever a tag is created. This job can remain disabled here, since we intend to use it only on [github.com/mozilla/bergamot-translator](https://github.com/mozilla/bergamot-translator).
Artifacts and releases will be created like this: https://github.com/andrenatal/bergamot-translator/releases
=> Adding circle ci job to push the wasm artifacts to github releases

.github/workflows/native.yml
This is a change that was missed in #252 that updates GitHub CI yaml files to run whole tests using the new separation (wasm, blocking, async, cli). 
Will be merged at own-risk after inspecting GitHub CI runs.
=> GitHub CI: Update YAML to run all tests on marian-full

.github/workflows/native.yml
Merging at own risk. Somehow the buggy workflow file passed a few CI runs until runners swapped hardware. :-|
=> Fix typo in BRT args on CI runs

src/translator/logging.h, src/translator/service.cpp, src/translator/service.h
[WIP] Preliminary piecing together of logging control functions from marian to allow some form of control on logging. 
My immediate use-case is to avoid all the dump coming which I don't need at:
```
(env) [jerin@eltbk lemonade]$ echo "Hello World" | bergamot translate -m en-de-tiny
[2021-12-31 11:35:19] [data] Loading SentencePiece vocabulary from file /home/jerin/.local/share/lemonade/models/ende.student.tiny11/vocab.deen.spm
[2021-12-31 11:35:19] Missing list of protected prefixes for sentence splitting. Set with --ssplit-prefix-file.
[2021-12-31 11:35:19] [data] Loading binary shortlist as /home/jerin/.local/share/lemonade/models/ende.student.tiny11/lex.s2t.bin false
[2021-12-31 11:35:19] [data] Lexical short list firstNum 50 and bestNum 50
[2021-12-31 11:35:19] [memory] Extending …
```
=> Turn logging off by default, allow turning on via config/cmdline

src/translator/response_builder.h
Fixes one half of #270. 
https://github.com/browsermt/bergamot-translator/pull/271 tries to provide a `sanitizeOptions`, which is perhaps more extensible. But such a function will have to be called at several sites increasing verbosity is my conclusion after experimenting in https://github.com/jerinphilip/bergamot-translator/pull/28.
Instead, we just pick-up `ResponseOptions.HTML` and place alignments with an `or` switch if `HTML` is on, irrespective of whatever value was given for `Alignment`s.
This way a client can go from:
```
$ cat | bergamot translate -m en-es-tiny --html=1 --alignment=1 
<a href="Tintin">Tintin</a>'s dog is a good dog.
El perro de <a href="Tintin">Tintín</a> es un buen perro.
```
to
```
$ cat | bergamot translate -m en-es-tiny --html=1 
<a href="Tintin">Tintin</a>'s …
```
=> Have alignments placed if HTML is on

src/tests/units/html_tests.cpp, src/translator/html.cpp, src/translator/html.h
This pull requests handles `<script>`, `<style>`, `` and `<? ?>` instructions. These were previously silently ignored, but are now treated as void elements like `<img>`: they are copied to the output based on their position in relation to other elements that do contain text.
Not entirely necessary for block-element-level translation, but nice to have when you're doing full-page translation like our little experiments with Python.
=> HTML transfer script/style/etc elements

src/tests/units/html_tests.cpp, src/translator/html.cpp
Allow the self-closing `/>` end for void tags. For non-void tags these were already "allowed" due to how the HTML parser works, but for elements where they actually occur, like `<br/>`, they caused a parse error. Support for them was not implemented since we only expect valid HTML5, e.g. the output of Firefox' `Element.innerHTML`.
Use case: [TranslateLocally uses Qt's HTML representation of rich text](https://github.com/XapaJIaMnu/translateLocally/pull/81). That HTML uses self-closing tags like `<meta .../>` and `<br/>`. Implementing a string replace operation that would only match these elements without parsing HTML is tricky. Fixing it in bergamot-translator is not.
Implementation: Currently `<img>` is marked as a void tag (an element which cannot have children or text, and therefore …
=> Accept XHTML-style self-closing void tags

app/bergamot.cpp, examples/run-native.sh, src/translator/byte_array_util.cpp, src/translator/service.h, src/translator/translation_model.cpp, src/translator/translation_model.h
Provides an additional constructor which takes care of the bundle loading inside the boundary of the source here, when a configuration file is supplied from a client like translateLocally or python bindings.  Once the config file is read, we have access to the information required to construct the `MemoryBundle`.
- The command-line application supplied from here, `app/bergamot` is configured to use the fast-load path now.
- Changes to binary-loading additionally revealed a bug in the example-run script used in docs and tied to CI and the fix is included.
-  Shortlist is made optional in the memory-bundle, making changes to `getModelMemoryFromConfig`.
Fixes #304.
Fixes #306.
See also: XapaJIaMnu/translateLocally#82.
PS: There is a need to refactor of `byte_array_utils`, aggressive …
=> Streamline memory-bundle loads

.github/workflows/windows.yml, CMakeLists.txt
Use https://github.com/cristianadam/ccache/releases/ to speed up windows
compilation.
Remove /Zi as it is unsupported by ccache at the moment. This is a debug
flag that was removed in upstream marian-dev
https://github.com/browsermt/marian-dev/pull/43. However, the bergamot
CMakeLists.txt which was originally taken from
marian maintained this under MSCV.
=> Speed up Windows CI with ccache

src/tests/common-impl.cpp, src/tests/common.h, src/translator/service.cpp
Previously BlockingService pivoting missed preproc and postproc for HTML leading to issues in WebAssembly API. This change adds fixes for the same, along with test coverage for the functionality over both async and blocking services.
=> Fix HTML with pivoting 

bindings/python/bergamot.cpp, src/translator/service.cpp
As a library, this is the more sane default. This also allows the
mechanism to convert into runtime errors in python, providing
informative messages to the user via pybind11 existing tooling.
=> Make default throw exception on abort for python

src/tests/units/html_tests.cpp, src/translator/html.cpp, src/translator/html.h, wasm/bindings/service_bindings.cpp
This change makes sure that errors are printed to the console in the WASM build. It also replaces the exceptions in `HTML` with `ABORT` macros to make sure something helpful is printed when they occur.
Note that the `onerror` handler is still called without an error message since it is just a forwarded call of `std::abort()`. Even if you hook into `onAbort`, it is called without arguments. However, if you do want to catch the error messages, you can hook into `printErr` which catches everything written to `std::cerr`. Which, thanks to the new default logging level, includes the exception message.
I've not changed this in `worker.js` because the default behaviour—print warnings to the terminal—is sufficient there. However, the example below might be useful for telemetry or Sentry …
=> Print errors by default in WASM build

src/translator/byte_array_util.cpp
Changes `ABORT` on non `.bin` model to an additional check for a `.npz` 
extension. If `.bin`, the fast load path is activated by returning `AlignedMemory`. 
Otherwise, the return of empty `AlignedMemory` causes fallback to
filesystem-based loads.
BRT: A test that checks if translation using `.npz` is approximately similar to 
that of default CLI translation is checked in to ensure stability going ahead.
Previously, we only supported `.bin` models' loading via a fast mmap 
path. While we had the underlying capability to load non `.bin` models, this 
was not exposed, encouraging fast loads. Loading `.npz` models are helpful 
for quick debugging and broader coverage of models available, which will 
enhance user experience at translateLocally and python bindings. 
Fixes #341.
See also: …
=> Add ability to load `.npz` models 

src/tests/common-impl.cpp, src/tests/wasm.cpp, src/translator/service.cpp, src/translator/service.h, wasm/bindings/response_options_bindings.cpp, wasm/test_page/js/worker.js
Changes signature of `BlockingService::{translate,pivot}Multiple` 
functions to take per input options, so a mix of HTML and plaintext
can be sent from the extension. Templating over testing is adjusted 
to allow for continuous evaluations by modifying the test code. 
Updates WebAssembly bindings to reflect the change in signature 
and the javascript test-page to work with the new bindings.
This change lacks an accompanying test specific to the mixed HTML 
and plaintext inputs.
Fixes: #345 
See also: https://github.com/mozilla/firefox-translations/issues/94
=> Allow per-input options

wasm/test_page/js/index.js, wasm/test_page/js/worker.js
Updated wasm test page:
- Now translate() JS API accepts ResponseOptions per batch item (courtesy of https://github.com/browsermt/bergamot-translator/pull/346)
- Fixed the logic to create `vector<ResponseOption>` that was introduced in https://github.com/browsermt/bergamot-translator/pull/346 and broke the test page
=> JS: Passing ResponseOptions for every item of translation batch API

bindings/python/bergamot.cpp, src/translator/request.cpp, src/translator/request.h, src/translator/service.cpp, src/translator/service.h, src/translator/translation_model.cpp, src/translator/translation_model.h
Hide `cache-mutex-buckets` from the user. Now configured to be equal to number
of workers. Python bindings which had exposed these are modified to reflect
the API change. `std::optional` enabled on cache, constructed only if enabled.
Pointers used are replaced with an equivalent `std::optional.`
Fixes: #317
=> Improve cache

.circleci/config.yml
Fixes https://github.com/browsermt/bergamot-translator/issues/335
The extension uses translator artifacts build in mozilla fork. Therefore, create github release via circleci only when running in mozilla fork.
Tested it here: https://app.circleci.com/pipelines/github/abhi-agg/bergamot-translator/96/workflows/10b2a8b5-32c0-4f36-abc1-1c379a1b876c
=> Create github release via CircleCI only for mozilla fork

wasm/test_page/js/index.js
Higher QE scores means better quality.
Changed the threshold to ~~`-0.5`~~ `ln(0.5) => -0.6931` as per discussions in QE meetings.
@mfomicheva @abarbosa94 @felipesantosk Please let me know if any of the above is wrong 👍🏾
=> Use right range and threshold for showing "bad" words/sentences

wasm/bindings/service_bindings.cpp, wasm/test_page/js/worker.js
Fixes: https://github.com/browsermt/bergamot-translator/issues/318
Modified the wasm test page and tested it there. It works.
Supervised QE binary models are being used for 3 language pairs.
=> JS: Using supervised QE models for available language pairs

wasm/test_page/js/index.js
https://github.com/browsermt/bergamot-translator/pull/358 changed a text area to a div to show quality UI renders, causing the code that swapped content on click of the button to populate instead with `undefined`.
This change uses `innerText` on the output to populate input to fix the issue.
=> JS: Fix swap button on test-page

src/translator/html.cpp
[The documentation](https://en.cppreference.com/w/cpp/string/byte/isspace) is explicit about only calling it with unsigned char, and Windows runtime is checking this.
=> Fix call to `std::isspace`

.github/workflows/build.yml, bindings/python/CMakeLists.txt, bindings/python/README.md, setup.py
Old GitHub CI using Ubuntu and MacOS explicitly and building wheels have
been removed in favour of the more portable pypa specified builds. These
wheels should work just as well across a wider range of distributions.
pybind11:CMakeLists.txt requires Development.Module instead of
Development.* to avoid Embed from getting in the way of manylinux
builds.
manylinux_x86_64 builds are added for cp3.6 - 3.10. The linux build
uses an old image via docker.  Since the docker images are able to use
shared ccache folder, builds quite fast on warm starts.
ccache usage in setup.py is now triggered by an environment variable.
This allows for builds not to fail if ccache not present.
On tag pushes corresponding to versions, CI is configured to deliver
built wheels to PyPI, reading from repository …
=> Set up python packaging for PyPI distribution

.github/workflows/build.yml, wasm/node-test.js
Imports
https://gist.github.com/jelmervdl/a4c8b6b92ad88a885e1cbd51c6ad4902 and
attach it to CI.  NodeJS-14 is failing on trying to use the WebAssembly
binary. So we use node-16 independently setup.  This paves way for more
complicated testing for WebAssembly bindings in the future. It should be possible
to remove minimal builds in favour of closer to WebAssembly tests following this 
change.
https://github.com/mozilla/firefox-translations/pull/353 phases out wormhole. 
This change removes the `.js` and `.wasm` with wormhole from the GitHub 
release done. (This does not edit Mozilla's CircleCI or files, nor attempt to 
remove WORMHOLE completely).
This also includes a fix for a `.js` and `.wasm` release broken in #424.
GitHub CI code verified to work as intended at at fork …
=> Basic HTML property testing for WebAssembly

.github/workflows/build.yml, wasm/README.md, wasm/node-test.js
This looked like the easiest way to provide some documentation & examples for the WASM API.
I've upgraded to node 18 because that allows us to use `fetch()` which matches what you would use in the browser.
Every line of code is annotated with some documentation on why it is there and what you can do with it.
=> Expand the node-test.js example code with documentation

src/translator/byte_array_util.cpp, src/translator/byte_array_util.h, src/translator/definitions.h, src/translator/translation_model.cpp, wasm/bindings/service_bindings.cpp
Adds the ability to use ensembles of models. This supports ensembles of binary- or npz-format models, as well as mixtures of both.
When all models in the ensembles are of binary format, the load from memory path is used. Otherwise, they are loaded via the file system. Enable log-level debug for output related to this.
=> Enables model ensembles

.gitignore
This adds more items to the project's .gitignore that are not being ignored. I could add them to my global gitignore, but it seems to make sense to add them to the project itself. Note that I added `/build` as well as `/build-native` as it's a common cmake practice to use `/build` as the build directory. The `emsdk` folder is generated by the `./build-wasm.sh` command.
=> Add more things to the gitignore that are not being ignored

CMakeLists.txt
I use vscode, and this is required to get the in-editor language server working. This is a standardized file that other editors can use as well to understand the C++ code.
https://clang.llvm.org/docs/JSONCompilationDatabase.html
The following is an example of the language server providing type information.
=> Generate a compile_commands.json by default with cmake

build-wasm.sh
The size of the wasm bundle affects the speed at which it can be loaded in the browser. This PR adds a report to the `build-wasm.sh` that shows the size both uncompressed, and compressed. The compressed size is generally what is actually downloaded by the end user.
Here is a sample output:
```
[ 98%] Linking CXX executable ../bergamot-translator-worker.js
'+sse2' is not a recognized feature for this target (ignoring feature)
'+sse2' is not a recognized feature for this target (ignoring feature)
'+ssse3' is not a recognized feature for this target (ignoring feature)
'+ssse3' is not a recognized feature for this target (ignoring feature)
warning: undefined symbol: int8_multiply_and_add_bias (referenced by top-level compiled C/C++ code)
warning: undefined symbol: int8_prepare_a (referenced …
```
=> Report the wasm size on builds

examples/run-native.sh
The model name in the download url for de-en translation in example script seems to have changed from `ende.student.tiny11.tar.gz` to `ende.student.tiny11.v2.93821e13b3c511b5.tar.gz`. I have updated the download url in this pr.
=> model name update in download url in example script

bindings/python/repository.py
models come in files named like `csen.student.base.v1.cd5418ba6a412fc7.tar.gz`, but the directory they create when extracted are named like `csen.student.base`. we therefore need to remove not just the extension but everything following and including the 3rd period
=> fix downloading of models in the python binding
